name: dev

on:
  push:
    branches:
    - develop
  workflow_dispatch:
    comment:
      description: 'Comment'
      required: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "8.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: "1.22.2"
      
      - name: Install Dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Tests
        run: flutter test --coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.14
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      - name: Build Debug Apk
        run: flutter build apk --debug
