name: deploy
on:
  push:
    branches:
    - master
  workflow_dispatch:
    comment:
      description: 'Comment'
      required: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: "8.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: "1.22.2"
      
      - name: Install Dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Tests
        run: flutter test
        
      - name: Build Apk
        run: flutter build apk --release

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          token: ${{ secrets.TOKEN }}
          commit: master
          tag: v1.0.${{ github.run_number }}
